# Generated by Django 5.1.4 on 2025-01-17 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_playlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playlist',
            old_name='songs',
            new_name='music',
        ),
    ]
