# Generated by Django 5.1.4 on 2025-01-20 07:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_playlist_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='artist_images/'),
        ),
        migrations.AddField(
            model_name='music',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='music_audio/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3', 'wav'])]),
        ),
    ]
