# Generated by Django 5.1.4 on 2025-01-23 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0006_artist_image_music_audio"),
    ]

    operations = [
        migrations.AlterField(
            model_name="music",
            name="artist",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="music",
                to="music.artist",
            ),
        ),
    ]
